name: flutter_voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 1.0.0
homepage: https://github.com/gamestap99/flutter_voice_message_player

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  just_audio: ^0.9.41
  syncfusion_flutter_sliders: ^26.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


